project_id = "zxjiugmqfzqluviuwztr"

[functions.send-survey-results]
verify_jwt = false

[functions.auto-send-survey-results]
verify_jwt = false

[functions.refresh-dashboard-cache]
verify_jwt = false
