// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zxjiugmqfzqluviuwztr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4aml1Z21xZnpxbHV2aXV3enRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4MDQyODcsImV4cCI6MjA2ODM4MDI4N30.exhEJujuL9-YVe8VW-J2-PoACUo1X1Cl2C0lL23K9x8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: sessionStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});